const analysisUi={
cnr:{copy:'⧉ Kopiraj pitanje',copied:'✓ Kopirano',open:'☷ Sva pitanja i odgovori',title:'Sva pitanja i odgovori',search:'Pretraga pitanja i odgovora na svim jezicima',copyAll:'⧉ Kopiraj spisak',count:n=>`${n} pitanja`,correct:'Tačan odgovor',close:'Zatvori',language:'Jezik spiska',image:'Slika uz pitanje',historyOpen:'◷ Istorija ispita',historyTitle:'Istorija ispita',exam:'Ispit',currentExam:'Trenutni ispit',historyEmpty:'Još nema sačuvanih ispita u ovom pregledaču'},
ru:{copy:'⧉ Скопировать вопрос',copied:'✓ Скопировано',open:'☷ Все вопросы и ответы',title:'Все вопросы и ответы',search:'Поиск вопросов и ответов на всех языках',copyAll:'⧉ Скопировать список',count:n=>`${n} ${n%10===1&&n%100!==11?'вопрос':n%10>=2&&n%10<=4&&(n%100<10||n%100>=20)?'вопроса':'вопросов'}`,correct:'Правильный ответ',close:'Закрыть',language:'Язык списка',image:'Изображение к вопросу',historyOpen:'◷ История экзаменов',historyTitle:'История экзаменов',exam:'Экзамен',currentExam:'Текущий экзамен',historyEmpty:'В этом браузере пока нет сохранённых экзаменов'},
en:{copy:'⧉ Copy question',copied:'✓ Copied',open:'☷ All questions and answers',title:'All questions and answers',search:'Search questions and answers in all languages',copyAll:'⧉ Copy list',count:n=>`${n} questions`,correct:'Correct answer',close:'Close',language:'List language',image:'Question image',historyOpen:'◷ Exam history',historyTitle:'Exam history',exam:'Exam',currentExam:'Current exam',historyEmpty:'No exams saved in this browser yet'},
de:{copy:'⧉ Frage kopieren',copied:'✓ Kopiert',open:'☷ Alle Fragen und Antworten',title:'Alle Fragen und Antworten',search:'Fragen und Antworten in allen Sprachen suchen',copyAll:'⧉ Liste kopieren',count:n=>`${n} Fragen`,correct:'Richtige Antwort',close:'Schließen',language:'Sprache der Liste',image:'Bild zur Frage',historyOpen:'◷ Prüfungsverlauf',historyTitle:'Prüfungsverlauf',exam:'Prüfung',currentExam:'Aktuelle Prüfung',historyEmpty:'In diesem Browser sind noch keine Prüfungen gespeichert'}
};
let analysisLanguage=language;
const localizedQuestion=(q,lang=language)=>({cnr:[q.question,q.options],ru:[q.questionRu,q.optionsRu],en:[q.questionEn,q.optionsEn],de:[q.questionDe,q.optionsDe]}[lang]);
const normalizeSearch=text=>String(text).toLocaleLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const searchableQuestion=q=>normalizeSearch([q.id,q.question,...q.options,q.questionRu,...q.optionsRu,q.questionEn,...q.optionsEn,q.questionDe,...q.optionsDe].join(' '));
const questionText=(q,lang=language)=>{const [title,answers]=localizedQuestion(q,lang);return `#${q.id}\n${title}\n${answers.map((answer,index)=>`${letters[index]}. ${answer}${index===q.correct?' ✓':''}`).join('\n')}\n${q.issue?q.issue[lang]:`${analysisUi[lang].correct}: ${letters[q.correct]}`}`};
async function copyText(text,button,lang=language){try{await navigator.clipboard.writeText(text)}catch{const area=document.createElement('textarea');area.value=text;document.body.append(area);area.select();document.execCommand('copy');area.remove()}const label=button.textContent;button.textContent=analysisUi[lang].copied;setTimeout(()=>button.textContent=label,1400)}
let analysisMode='all';
let analysisExamId=null;
const analysisLocales={cnr:'sr-Latn-ME',ru:'ru-RU',en:'en-US',de:'de-DE'};
function selectedExam(){return examHistory.find(entry=>entry.id===analysisExamId)}
function analysisQuestions(){if(analysisMode!=='history')return questions;const byId=new Map(questions.map(q=>[q.id,q]));return (selectedExam()?.questionIds||[]).map(id=>byId.get(id)).filter(Boolean)}
function renderHistoryOptions(){const select=$('analysis-exam');select.replaceChildren(...examHistory.map((entry,index)=>{const option=document.createElement('option');option.value=entry.id;const date=new Date(entry.createdAt).toLocaleString(analysisLocales[analysisLanguage],{dateStyle:'short',timeStyle:'medium'});const current=entry.id===currentExamId&&questionMode==='exam'?`${analysisUi[analysisLanguage].currentExam} · `:'';option.textContent=`${current}${analysisUi[analysisLanguage].exam} ${examHistory.length-index} · ${date} · ${ui[analysisLanguage].categories[entry.category]||entry.category}`;return option}));if(!selectedExam())analysisExamId=examHistory[0]?.id||null;select.value=analysisExamId||''}
function translateDialog(){const x=analysisUi[analysisLanguage];$('analysis-language').value=analysisLanguage;$('analysis-language').ariaLabel=x.language;$('analysis-title').textContent=analysisMode==='history'?x.historyTitle:x.title;$('analysis-search').placeholder=x.search;$('copy-all').textContent=x.copyAll;$('close-analysis').ariaLabel=x.close;$('analysis-history-tools').hidden=analysisMode!=='history';$('analysis-exam-label').textContent=x.exam;renderHistoryOptions();renderAnalysis()}
function translateAnalysis(){const x=analysisUi[language];$('copy-current').textContent=x.copy;$('open-analysis').textContent=x.open;$('open-history').textContent=x.historyOpen}
function renderAnalysis(){const query=normalizeSearch($('analysis-search').value.trim());const visible=analysisQuestions().filter(q=>!query||searchableQuestion(q).includes(query));$('analysis-count').textContent=analysisMode==='history'&&!examHistory.length?analysisUi[analysisLanguage].historyEmpty:analysisUi[analysisLanguage].count(visible.length);$('analysis-list').replaceChildren(...visible.map(q=>{const [title,answers]=localizedQuestion(q,analysisLanguage);const article=document.createElement('article');article.className='analysis-item';const heading=document.createElement('h3');heading.textContent=`#${q.id} · ${title}`;article.append(heading);if(q.hasDiagram&&q.diagramImage){const img=document.createElement('img');img.className='analysis-image';img.src=`questions/${q.diagramImage}`;img.alt=`${analysisUi[analysisLanguage].image} #${q.id}`;img.loading='lazy';article.append(img)}if(q.issue){const note=document.createElement('p');note.className='analysis-issue';note.textContent=q.issue[analysisLanguage];article.append(note)}const list=document.createElement('ol');list.type='A';answers.forEach((answer,index)=>{const li=document.createElement('li');li.textContent=answer;if(index===q.correct){li.className='analysis-correct';li.insertAdjacentText('beforeend',' ✓')}list.append(li)});article.append(list);const source=document.createElement('details');source.className='analysis-source';const summary=document.createElement('summary');summary.textContent=ui[analysisLanguage].source;const sourceImage=document.createElement('img');sourceImage.width=1100;sourceImage.height=150;sourceImage.alt=`${ui[analysisLanguage].source.replace('▣ ','')} #${q.id}`;sourceImage.loading='lazy';source.ontoggle=()=>{if(source.open&&!sourceImage.src)sourceImage.src=`questions/${q.image}`};source.append(summary,sourceImage);article.append(source);return article}))}
function openAnalysis(mode){analysisMode=mode;analysisLanguage=language;$('analysis-search').value='';if(mode==='history')analysisExamId=examHistory.find(entry=>entry.id!==currentExamId)?.id||examHistory[0]?.id||null;translateDialog();$('analysis-dialog').showModal();$('analysis-search').focus()}
$('copy-current').onclick=()=>{const q=current();if(q)copyText(questionText(q),$('copy-current'))};
$('open-analysis').onclick=()=>openAnalysis('all');
$('open-history').onclick=()=>openAnalysis('history');
$('close-analysis').onclick=()=>$('analysis-dialog').close();
$('analysis-dialog').onclick=e=>{if(e.target===$('analysis-dialog'))$('analysis-dialog').close()};
$('analysis-search').oninput=renderAnalysis;
$('analysis-language').onchange=e=>{analysisLanguage=e.target.value;translateDialog()};
$('analysis-exam').onchange=e=>{analysisExamId=e.target.value;renderAnalysis()};
$('copy-all').onclick=()=>copyText(analysisQuestions().map(q=>questionText(q,analysisLanguage)).join('\n\n'),$('copy-all'),analysisLanguage);
document.querySelectorAll('[data-lang]').forEach(button=>button.addEventListener('click',translateAnalysis));
translateAnalysis();
