let questions=[];let order=[];let position=0;let selected=null;let answered=false;let correct=0;let wrong=0;let language='ru';let answerMode='random';let optionOrders={};
const $=id=>document.getElementById(id);const letters=['A','B','C'];
function current(){return questions.find(q=>q.id===order[position])}
function shuffledOptions(){const ids=[0,1,2];for(let i=ids.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[ids[i],ids[j]]=[ids[j],ids[i]]}return ids}
function prepareOptionOrders(){optionOrders=Object.fromEntries(questions.map(q=>[q.id,answerMode==='random'?shuffledOptions():[0,1,2]]))}
function randomPage(from,to){const available=[];for(let page=from;page<=to;page++){if(questions.some(q=>q.page===page))available.push(page)}return available[Math.floor(Math.random()*available.length)]}
function buildExam(){const pages=[[1,17],[18,57],[58,84],[85,93]].map(([from,to])=>randomPage(from,to));return pages.flatMap(page=>questions.filter(q=>q.page===page).map(q=>q.id))}
function render(){const q=current();if(!q)return;const opts=language==='ru'?q.optionsRu:q.options;const displayed=optionOrders[q.id]||[0,1,2];const total=correct+wrong;
 $('progress-label').textContent=`Вопрос ${position+1} из ${order.length}`;$('page-label').textContent=`Лист источника ${q.page}`;$('progress').style.width=`${((position+(answered?1:0))/order.length)*100}%`;
 $('correct').textContent=correct;$('wrong').textContent=wrong;$('percent').textContent=`${total?Math.round(correct/total*100):0}%`;$('question').textContent=language==='ru'?q.questionRu:q.question;$('language-label').textContent=language==='ru'?'◎ Готовый русский перевод':'◎ Crnogorski original';
 $('diagram').hidden=!q.hasDiagram;$('diagram-img').src=`questions/${q.image}`;$('diagram-cover').hidden=answered;$('source-img').src=`questions/${q.image}`;$('source-cover').hidden=answered;
 $('options').replaceChildren(...displayed.map((originalIndex,displayIndex)=>{const text=opts[originalIndex];const b=document.createElement('button');b.className='option'+(selected===originalIndex?' selected':'')+(answered&&originalIndex===q.correct?' right':'')+(answered&&selected===originalIndex&&originalIndex!==q.correct?' wrong':'');b.disabled=answered;b.setAttribute('role','radio');b.setAttribute('aria-checked',selected===originalIndex);const badge=document.createElement('span');badge.className='badge';badge.textContent=answered&&originalIndex===q.correct?'✓':answered&&selected===originalIndex&&originalIndex!==q.correct?'×':letters[displayIndex];const label=document.createElement('span');label.textContent=text;b.append(badge,label);b.onclick=()=>{selected=originalIndex;render()};return b}));
 const feedback=$('feedback');feedback.hidden=!answered;if(answered){const good=selected===q.correct;feedback.className=`feedback ${good?'good':'bad'}`;feedback.innerHTML=`<strong>${good?'Правильно':'Неверно'}</strong><span></span>`;feedback.querySelector('span').textContent=`Правильный ответ: ${opts[q.correct]}`}
 const primary=$('primary');primary.disabled=selected===null;primary.textContent=answered?(position===order.length-1?'Собрать новый экзамен':'Следующий вопрос →'):'Проверить ответ';}
function newExam(){order=buildExam();prepareOptionOrders();position=0;selected=null;answered=false;render()}
function resetResult(){position=0;selected=null;answered=false;correct=0;wrong=0;prepareOptionOrders();render()}
$('primary').onclick=()=>{if(!answered){answered=true;if(selected===current().correct)correct++;else wrong++}else if(position<order.length-1){position++;selected=null;answered=false}else newExam();render()};
$('new-exam').onclick=newExam;$('reset').onclick=resetResult;document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{language=b.dataset.lang;document.querySelectorAll('[data-lang]').forEach(x=>x.classList.toggle('active',x===b));render()});document.querySelectorAll('[data-answer-mode]').forEach(b=>b.onclick=()=>{answerMode=b.dataset.answerMode;prepareOptionOrders();document.querySelectorAll('[data-answer-mode]').forEach(x=>x.classList.toggle('active',x===b));render()});
fetch('questions.json').then(r=>{if(!r.ok)throw new Error();return r.json()}).then(data=>{questions=data;$('question-count').textContent=data.length;newExam()}).catch(()=>{$('question').innerHTML='<span class="fatal">Не удалось загрузить вопросы. Обновите страницу.</span>'});
